backend:
  name: git-gateway
  branch: tower
media_folder: static/upload
public_folder: /upload
slug:
  encoding: "ascii"
  clean_accents: true
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, cs]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en
media_library:
  name: cloudinary
  config:
    cloud_name: lukasfabik
    api_key: 818759917278117
collections:
  - name: 'blog'
    label: 'Blog'
    i18n: true
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false, i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Meta title', name: 'meta_title', widget: 'string', i18n: true }
      - { label: 'Meta description', name: 'meta_description', widget: 'string', i18n: true }
      - { label: 'Preview image', name: 'image_preview', widget: 'image', required: false, tagname: '', i18n: true }
      - { label: 'Main image', name: 'image_main', widget: 'image', required: false, tagname: '', i18n: true }
      - { label: 'Meta image', name: 'image_meta', widget: 'image', required: false, tagname: '', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
  - name: 'tutorials'
    label: 'Tutorials'
    i18n: true
    folder: 'content/education/tutorials'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false, i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Slug', name: 'slug', widget: 'string', i18n: true }
      - { label: 'Weight', name: 'weight', widget: 'number', default: 0, value_type: 'int', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Meta title', name: 'meta_title', widget: 'string', i18n: true }
      - { label: 'Meta description', name: 'meta_description', widget: 'string', i18n: true }
      - { label: 'Preview image', name: 'image_preview', widget: 'image', required: false, tagname: '', i18n: true }
      - { label: 'Main image', name: 'image_main', widget: 'image', required: false, tagname: '', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
  - name: 'projects'
    label: 'Projects'
    i18n: true
    folder: 'content/education/projects'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false, i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Slug', name: 'slug', widget: 'string', i18n: true }
      - { label: 'Weight', name: 'weight', widget: 'number', default: 0, value_type: 'int', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Meta title', name: 'meta_title', widget: 'string', i18n: true }
      - { label: 'Meta description', name: 'meta_description', widget: 'string', i18n: true }
      - { label: 'Preview image', name: 'image_preview', widget: 'image', required: false, tagname: '', i18n: true }
      - { label: 'Main image', name: 'image_main', widget: 'image', required: false, tagname: '', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
